name: Sync to GitHub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitHub
        run: |
          git remote add github https://${{ secrets.GH_MIRROR_TOKEN }}@github.com/Suparious/${{ gitea.repository }}.git || true
          git push github HEAD:main --force
